version: '3.4'

services:
  featurehub:
    image: featurehub/party-server:latest
    restart: always
    volumes:
      - featurehub-h2-data:/db
    ports:
      - 8085:8085
       
  rhubarbfillingservice:
    image: ${DOCKER_REGISTRY-}rhubarbfillingservice
    build:
      context: .
      dockerfile: RhubarbFillingService/Dockerfile
    deploy:
      mode: replicated
      replicas: 2

  bakepie:
    image: ${DOCKER_REGISTRY-}bakepie
    build:
      context: .
      dockerfile: BakePie/Dockerfile
    depends_on:
      - featurehub

volumes:
  featurehub-h2-data:

